apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "earlypass.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "earlypass.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  {{- if .Values.config.baseUrl }}
  BASE_URL: {{ .Values.config.baseUrl | quote }}
  {{- end }}
  {{- if .Values.config.trustedProxies }}
  TRUSTED_PROXIES: {{ .Values.config.trustedProxies | quote }}
  {{- end }}
  DEV_MODE: {{ .Values.config.devMode | quote }}
  {{- if .Values.config.otelEndpoint }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otelEndpoint | quote }}
  {{- end }}
