apiVersion: v1
kind: Service
metadata:
  name: {{ include "earlypass.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "earlypass.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "earlypass.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.config.port | int }}
      targetPort: http
      protocol: TCP
